### ISSUE TITLE
Unable to connect to the R Session on Mac

### ISSUE THREAD

**Issue by anleopa** [rocker-org/rocker-versioned2#713] opened 2023-10-17 09:04 UTC
### Container image name

rocker/rstudio:latest

### Container image digest

rocker/rstudio@sha256:e2c479fd17a6caca31dd85832d6b4155173723adea36786170a370b195bbb245

### What operating system are you seeing the problem on?

macOS

### System information

- Docker version:
- Mac model: Mac Book Air M1
- OS: Big Sur 11.6

### Bug description

Cannot access the RStudio environment. Error message:

"Could not connect to the R Session on R Studio Server. Unable to connet to service(1)."

### How to reproduce this bug?

```sh
docker container run --platform linux/amd64 --rm -dt -ti -e DISABLE_AUTH=true -p 8787:8787 --name rstudio rocker/rstudio
```

**Comment by eitsupi** [comment] 2023-10-17 11:05
Duplicate of #144

Please

1. Use linux/arm64 platform image
2. Not to use RStudio Server

**Closed by eitsupi** 2023-10-17 11:05 UTC
Labels: bug, question

**Comment by anleopa** [comment] 2023-10-17 18:52
Thanks for the reply but I don’t fully understand the answer. Following the thread of Issue 144 it says:rocker/rstudio:latest arm64 image has been pushed to DockerHub today.I thought that downloading this image will solve the problem. This is the image I have downloaded and it still doesn’t work. What does “not to use RStudio Server” means?El 17 oct 2023, a las 13:06, eitsupi ***@***.***> escribió:﻿
Duplicate of #144
Please

Use linux/arm64 platform image
Not to use RStudio Server

**Comment by eitsupi** [comment] 2023-10-18 12:23
Ah, sorry if it's hard to understand. This meant that there were two workarounds.

**Comment by anleopa** [comment] 2023-10-18 12:45
Oh! Thanks! 😅And what is the Linux/amd64 image. I thought it was the one tagged as latest.El 18 oct 2023, a las 14:23, eitsupi ***@***.***> escribió:﻿
Ah, sorry if it's hard to understand. This meant that there were two workarounds.

**Comment by anleopa** [comment] 2023-10-18 12:49
Great! Thanks!El 18 oct 2023, a las 14:47, eitsupi ***@***.***> escribió:﻿

what is the Linux/amd64 image. I thought it was the one tagged as latest.

See the Docker's docs https://docs.docker.com/build/building/multi-platform/
