### ISSUE TITLE
Rendering R Markdown on RStudio Server requires an updated version of the `markdown` package

### ISSUE THREAD

**Issue by rgaiacs** [rocker-org/rocker-versioned2#525] opened 2022-08-31 07:31 UTC
### Container image name

rocker/verse:latest

### Container image digest

rocker/verse@sha256:70b28cc0719b2ffd3ae377bc6788ca7253b8c9286a3a2eebb714c73585f42ed2

### What operating system are you seeing the problem on?

Linux

### System information

- `Linux 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 GNU/Linux`
- Docker version 20.10.17, build 100c701
- Docker Compose version v2.6.0

### Bug description

Click the `knit` button brings up the `Install Required Packages` pop up window

![Screenshot from 2022-08-31 15-19-52](https://user-images.githubusercontent.com/1506457/187618861-c2a3229d-1993-42e1-9a61-a7e5cb71853e.png)

But `rmarkdown` is already installed.

```
> library(rmarkdown)
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rmarkdown_2.16

loaded via a namespace (and not attached):
 [1] compiler_4.2.1  fastmap_1.1.0   cli_3.3.0       htmltools_0.5.3 tools_4.2.1     rstudioapi_0.14 knitr_1.40      xfun_0.32       digest_0.6.29   rlang_1.0.4    
[11] evaluate_0.16 
```

### How to reproduce this bug?

Use the following `docker-compose.yml`:

```yml
services:
  dev:
    image: rocker/verse
    environment:
      USERID: 1001
      PASSWORD: 12345678
    ports:
      - 8787:8787
```

Run

```sh
docker compose up
```

1. Open RStudio IDE
2. Create a new R Markdown file
3. `knit` the R Markdown file

**Comment by eitsupi** [comment] 2022-08-31 08:42
Hello. I think this is a requirement of RStudio Server (not a bug).
I don't know why RStudio Server requires [the `markdown` package](https://github.com/rstudio/markdown) here.

> But `rmarkdown` is already installed.

Please read the popup carefully.
This is the `markdown` package, not the `rmarkdown` package.

I am wondering if this needs to be pre-installed since it can be installed when users render RMarkdown on RStudio IDE.
I am aware that the `markdown` package has generally been superseded by the `rmarkdown` package and is therefore no longer in use. [^1]

[^1]: <https://www.rstudio.com/blog/r-markdown-v2/>

**Comment by eitsupi** [comment] 2022-08-31 08:48
It seems tracked on this issue rstudio/rstudio#9861
According to this issue, RStudio IDE does not actually need this package either. (i.e., this behavior is a bug of RStudio IDE and the rendering does not actually require this package)

So I close this.

**Closed by eitsupi** 2022-08-31 08:48 UTC
