### ISSUE TITLE
rocker/rstudio not supported for M series Macs?

### ISSUE THREAD

**Issue by rkrug** [rocker-org/rocker-versioned2#645] opened 2023-04-26 09:13 UTC
Hi

I am trying toi install an RStudio server on a M1 Mac using there rocker images. But when trying to pull rocker/rstudio, I get an `no matching manifest for linux/arm64/v8 in the manifest entries` error (rocker/r-ver pulled fine). Is this a n oversight, that these images do not support M1 Macs, or is it on purpose?

**Comment by eitsupi** [comment] 2023-04-26 10:30
Hello. I believe this is a duplicate of #144.

The reason is that there is no Linux arm64 release in the released version of RStudio Server.

Since there are arm64 build of RStudio daily builds, there are linux/arm64 versions of `rocker/rstudio:latest-daily` which includes RStudio Server daily builds.
https://github.com/rocker-org/rocker-versioned2/issues/144#issuecomment-1363791740

**Closed by eitsupi** 2023-04-26 10:30 UTC
