### ISSUE TITLE
OlsonNames() not found - tzdata not installed in r-ver:4.2.2

### ISSUE THREAD

**Issue by dpprdan** [rocker-org/rocker-versioned2#558] opened 2022-11-02 11:23 UTC
### Container image name

rocker/r-ver:4.2.2

### Container image digest

rocker/r-ver@sha256:8fc484926cce24595dad9f380405325788a43f422a47d81d28379a831bbc2ec4

### What operating system are you seeing the problem on?

Windows

### System information

- Microsoft Windows NT 10.0.19044.0
- Docker version 20.10.17, build 100c701

### Bug description

`OlsonNames()` does not find an Olson database. 

```r
> OlsonNames()
character(0)
Warning message:
In OlsonNames() : no Olson database found
```

With the r-ver:4.2.1 (rocker/r-ver@sha256:84dbe29c3218221af453eca9bf95249d605920d9aa03598fcc96767242b7ea5e) I get:

```r
> OlsonNames()
  [1] "Africa/Abidjan"                   "Africa/Accra"
  [3] "Africa/Addis_Ababa"               "Africa/Algiers"
[...]
```

(My initial problem that I cannot set a timezone on a Postgres connection with `RPostgres::dbConnect(timezone = "Europe/Berlin")`, but this is the root cause, I assume).

The 4.2.2 image(s) do(es) not contain the tzdata apt package:

```bash
root@30e36fb80943:/# apt list tzdata
Listing... Done
tzdata/now 2022e-0ubuntu0.22.04.0 all [residual-config]
```

4.2.1 does

```r
root@7878c49ca1e4:/# apt list tzdata
Listing... Done
tzdata/now 2022e-0ubuntu0.20.04.0 all [installed,local]
```

The build action for 4.2.2 [shows that tzdata is removed](https://github.com/rocker-org/rocker-versioned2/actions/runs/3360364550/jobs/5569477110#step:7:9807) ([here as well](https://github.com/rocker-org/rocker-versioned2/actions/runs/3360364550/jobs/5569477110#step:7:14274)).

cf  #86 

### How to reproduce this bug?

```sh
docker run --rm -i -t rocker/r-ver:4.2.2
```

```r
OlsonNames()
```

**Comment by eitsupi** [comment] 2022-11-02 11:28
Duplicate of #557

**Closed by eitsupi** 2022-11-02 11:28 UTC
Labels: bug
