### ISSUE TITLE
`grDevices::grSoftVersion()` warning: libxt6 missing

### ISSUE THREAD

**Issue by dpprdan** [rocker-org/rocker-versioned2#731] opened 2023-11-17 12:13 UTC
### Container image name

ghcr.io/rocker-org/r-ver:4.3.2

### Container image digest

ghcr.io/rocker-org/r-ver@sha256:459ee9f77ebbbe99f91e24259bbbe60f744045908bd46596463b8c3d909a6a7f

### What operating system are you seeing the problem on?

Windows

### System information

- Docker version 24.0.6, build ed223bc
- Windows 11 (23H2, 10.0.22631.0)

### Bug description

I'd like to come back to an aspect of #135, in particular the warning `grSoftVersion()` throws:

```r
> grDevices::grSoftVersion()
   cairo  cairoFT    pango   libpng     jpeg  libtiff
"1.16.0"       "" "1.50.6"       ""       ""       ""
Warning message:
In grDevices::grSoftVersion() :
  unable to load shared object '/usr/local/lib/R/modules//R_X11.so':
  libXt.so.6: cannot open shared object file: No such file or directory
```

Can we add libxt6 to make the warning go away? Caveat: [libxt6](https://packages.ubuntu.com/search?keywords=libxt6) doesn't seem to be available in the image's apt sources at the moment:

```bash
root@90aebbd437ae:/# apt list libxt6
Listing... Done
```

I see the warning also always after rendering a quarto (with knitr engine) or rmarkdown document, if it includes a plot (base or ggplot). I assume this is due to one of {grDevices} calls from {knitr}, but I haven't been able to pin down where exactly, yet.

See also https://notes.rmhogervorst.nl/post/2020/09/23/solving-libxt-so-6-cannot-open-shared-object-in-grdevices-grsoftversion/

### How to reproduce this bug?

```sh
PS C:\> docker run --rm -ti -p 8000:8000 ghcr.io/rocker-org/r-ver:4.3.2 R

R version 4.3.2 (2023-10-31) -- "Eye Holes"
[...]

> grDevices::grSoftVersion()
   cairo  cairoFT    pango   libpng     jpeg  libtiff
"1.16.0"       "" "1.50.6"       ""       ""       ""
Warning message:
In grDevices::grSoftVersion() :
  unable to load shared object '/usr/local/lib/R/modules//R_X11.so':
  libXt.so.6: cannot open shared object file: No such file or directory
> quit()
```

To reproduce with rmarkdown document rendering: 

```
docker run --rm -ti -e PASSWORD=yourpassword -p 8787:8787 rocker/rstudio
```

- Open `localhost:8787` and log into RStudio.
- Create a new rmarkdown sample document (File > New > RMarkdown).
- Knit via "Knit" button
- See abovementioned warning in the "Render" pane.
```

**Comment by eitsupi** [comment] 2023-11-17 12:15
I often see this warning, but it doesn't actually cause any harm, so I'm against adding a package just to get rid of it.

**Comment by dpprdan** [comment] 2023-11-17 12:40
Well, then there's the question of why there is a warning to begin with?

By contrast, `rocker/r-ubuntu:22.04` shows:

```r
> grDevices::grSoftVersion()
                   cairo                  cairoFT                    pango
                "1.16.0"                       ""                 "1.50.6"
                  libpng                     jpeg                  libtiff
                "1.6.37"                    "8.0" "LIBTIFF, Version 4.3.0"
```

and 

```bash
PS C:\> docker run --rm -ti -p 8000:8000 rocker/r-ubuntu:22.04 bash
root@bf2d383843dd:/# apt list libxt6
Listing... Done
libxt6/now 1:1.2.1-1 amd64 [installed,local]
```

**Comment by cboettig** [comment] 2023-11-19 20:25
It's a good question, the warning is definitely a distraction and a nuisance.  As you probably know, RStudio doesn't use the X11 windowing system for a graphic interface but uses a browser-based interface instead, and while it's possible to get a docker app to use the desktop X11 window system, it's not the standard approach in Docker (e.g. the run commands you show don't bind to the local X11 system and so can't render X11 windows anyway).  In contrast, command-line desktop users expect R to be able to open a display for plots and stuff in the local windowing system, so the debian (and hence ubuntu) `r-base-core` package includes a dependency on X11.  

The "versioned stack" (rocker/r-ver, rocker/rstudio, etc) builds R from source and drops numerous non-essential dependencies like X11 in order to keep image size a bit smaller (though not as aggressively as some extra-minimal builds that remove compilers etc).  The r-ubuntu stack installs R binaries from apt and thus inherits the standard debian dependencies there.  (X11 libraries including libxt are certainly available in the upstream ubuntu repos on r-ver etc; though note you may need to run `apt-get update` first because we also clear apt cache to save space, following common docker best practices)

It's not entirely clear to me why `grDevices`  has to throw a warning in this context where X11 libraries are not all included , but that might be better addressed by the grDevices developers?  

I'm happy to try and explore with you -- I've seen students get confused by this warning being triggered by various libraries too and agree it would be better if it didn't appear.  I think this partly just reflects package developers still adapting from a world that used to assume all software run in a local windowed system, and in containers or over browsers etc.

**Comment by eddelbuettel** [comment] 2023-11-19 20:57
Good points. The question is whether we think of these containers as _RStudio containers_ (hence no x11) or _R containers_.  I had some `alias` settings here but it took me a moment but then

```
docker run --rm -it -u 1000  -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix \
       -h $HOSTNAME -v $HOME/.Xauthority:/home/docker/.Xauthority rocker/r-base R
```

launched R in such a way that `plot(1:10)` did in fact open the usual x11 display window.    But that may not be suitable for an RStudio context so it all depends.

**Comment by eitsupi** [comment] 2023-11-19 23:03
It says here that even if we don't use RStudio IDE, a browser-based graphics device like `httpgd` would be a better experience than X11.
https://rocker-project.org/use/gui.html

**Comment by dpprdan** [comment] 2023-11-20 15:14
Thank you all, I understand the issue a bit better now.

> the warning is definitely a distraction and a nuisance [...] I've seen students get confused by this warning

Yeah, me too. I stumbled over it now because I saw it just before an - as it turned out - unrelated, but also graphics-error. As a result, this (as I know now) benign warning sent me down an (avoidable) debugging rabbit-hole. So while this may not be a _technical_ issue, per se, it is indeed a distraction which is prone to cause confusion. Especially considering how widespread the usage of these images and how [often we see](https://github.com/rocker-org/rocker-versioned2/issues/731#issuecomment-1816302090) this warning.

> The question is whether we think of these containers as _RStudio containers_ (hence no x11) or _R containers_.

That is a fundamental question indeed (and has been partly [raised earlier](https://github.com/rocker-org/rocker-versioned2/issues/315)). Even more so, if image size has any relevance. 

As an aside, I can say that of all the occasions I've used ~~the versioned stack~~ the pre-built tidyverse or geospatial images in the past, I have (almost) never needed nor used RStudio. In fact, in this particular case I am using the image in a [devcontainer](https://github.com/rocker-org/devcontainer-images/) with VS Code.

As it stands now, tidyverse, verse, geospatial and binder are indeed _RStudio_ images, while r-ver as well as all shiny- and cuda-based images are not (AFAICT). This in turn means, however, that the "RStudio doesn't use X11, hence we do not need to install all X11 libs" argument doesn't have much merrit here, right?

Btw, do you mean that if we think of them as R images, they _ought to_ contain X11, @edelbuettel?

> The "versioned stack" [...] drops numerous non-essential dependencies like X11

FWIW r-ver still contains `libx11-6`, `libx11-data`, `libx11-xcb1`, `x11-common`, `libxau6`, `libxext6`, and `libxi6` at least, presumably because those _are_ essential to some extent? Any idea why `libxt6` [is removed](https://github.com/rocker-org/rocker-versioned2/blob/62a752289fd278370b72a8dafc8a1c0501bd6019/scripts/install_R_source.sh#L160-L162) but these aren't?

> It's not entirely clear to me why `grDevices` has to throw a warning in this context where X11 libraries are not all included , but that might be better addressed by the grDevices developers?

This reminds me of the recent [wayland support thread](https://stat.ethz.ch/pipermail/r-devel/2023-October/082959.html) on the r-devel mailing list, in the sense that assuming all X11 libraries might even be wrong on "local windowed systems"? So it might be worth pursueing this further?

> we also clear apt cache to save space, following common docker best practices

Of course, sorry, I hadn't thought about that while writing the OP.

**Comment by eddelbuettel** [comment] 2023-11-20 15:19
> Btw, do you mean that if we think of them as R images, they ought to contain X11, @edelbuettel?

I gave an example using rocker/r-base to plot data. For which R uses x11.

**Comment by cboettig** [comment] 2023-11-20 15:47
Correct, r-ver removes build dependencies but not run-time dependencies, as you saw in the recipe.  As this discussion highlights, sometimes an apt package may bring in it's own dependencies, and of course r-base-core isn't the only package out there that has some implicit dependency on some part of the X11 ecosystem, so my guess is that is why packages you mention are still included.  



Just a note -- I disagree entirely that these are somehow fundamentally "RStudio" containers because some of them happen to have rstudio, just as I disagree entirely that the r-ubuntu stack are somehow fundamentally "X11" containers.   

Nothing I mentioned above has anything to do with RStudio specifically -- it's every bit as true for VSCode!   It's true of everything that runs in a docker container which doesn't explicitly bind X11 windowing system in the way Dirk showed above:

```
docker run -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix \
       -h $HOSTNAME -v $HOME/.Xauthority:/home/docker/.Xauthority 
```

Unless you are using all of these commands in every docker run, you can't use (most of) X11 anyway.  That does not make it an "RStudio" container.  It might have been cleaner if I just said X11 doesn't work at all from docker, which would cover > 99% of docker use but as Dirk points out it is technically possible and some users still make use of this, especially for GL bindings etc.  This really has nothing to do with RStudio in particular.  RStudio, VSCode, and most other such front ends built in the last decade or so use browser-based architecture rather than binding to X11, and as such can open additional 'windows' over ports like httpg uses.  The "versioned stack" isn't versioned because "it has rstudio" (the r-ver image does not, the design works equally well with other modern editors like vscode, and all of these images have features that not all users use -- just as the  r-ubuntu images aren't "X11 images") .  

The core difference between what we call the "r-versioned" stack and the r-ubuntu stack is simply whether R is installed from apt or built from source.  This extends to R packages as well, the versioned stack tends to install these from Posit Package Manager Binaries or from source, while the r-ubuntu stack is optimized to install R packages from `apt-get` repos. Each of these install strategies has advantages and disadvantages depending on user patterns and what's important.  

I know we could do a better job of explaining all this in the docs!  Part of the trouble is of course that most of the time the user doesn't really need to know or care about all these details, until of course, they do.  hope this helps!

**Comment by eddelbuettel** [comment] 2023-11-20 16:04
(@cboettig All good. But if I may, maybe avoid talking about `r-ubuntu` as the alternative to `r-ver`.  That branch is kinda stale / less used and it is all even more complicated as the non-versioned stack also contains Debian and Ubuntu. I think it would be more expressive and valuable to talk about `r-base` (which we export after all to Docker) and/or `r-base / r2u` as the latter is getting a bit more mind share.  Anyway -- it's all a documentation "mess" of our own making and a "nice problem to have" as it all works as designed.  Now, _explaining it all_ is another task...)

**Comment by dpprdan** [comment] 2023-12-21 17:01
Coming back to this, I tried Dirk's X11-enabling docker command and to my surprise it even works on WSL on Windows 11 with the `rocker/r-base` image. 

![grafik](https://github.com/rocker-org/rocker-versioned2/assets/1423562/0ca8cf9b-743f-47dc-bbf0-9fa17c051b28)

With `rocker/r-ver`, however, I get an error in R that the X11 module cannot be loaded:

```R
daniel@Notebook-DP:~$ docker run --rm -it -u 1000  -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -h $HOSTNAME -v $HOME/.Xauthority:/home/docker/.Xauthority rocker/r-ver:4.3.2 R

R version 4.3.2 (2023-10-31) -- "Eye Holes"
[...]

> plot(pressure)
Error in (function (display = "", width, height, pointsize, gamma, bg,  :
  X11 module cannot be loaded
In addition: Warning message:
In grSoftVersion() :
  unable to load shared object '/usr/local/lib/R/modules//R_X11.so':
  libXt.so.6: cannot open shared object file: No such file or directory
```

So it appears that X11 does not work with r-ver at the moment. 

The question then is, is X11 supposed to work (to the extent used by R) with the r-ver image? 

If it is, it should be fixed. Which means, it seems to me, that at least `libxt6` needs to be included in the image.

If it isn't, it might be worth considering building R `--without-x`. 

(AFAIU It is technically possible to build R `--without-x` since v2.14, but apparently there were some issues, the peculiarities of which I don't fully understand, and those issues seem to have been resolved in R 4.1.).

**Comment by cboettig** [comment] 2023-12-23 02:06
@dpprdan iiuc, it works fine once libxt6 is installed, yes?  So a user can just install that if they need x11 and they should be good to go, right?  Building R without x support on the other hand would make it a lot harder to opt in with a downstream dockerfile (i.e. would require rebuilding R instead of installing one lib?)   Am I missing something?

**Comment by dpprdan** [comment] 2024-01-18 16:16
This is how I see the issue:

1. I think we have established that the warning caused by the missing libxt6 package is "definitely a distraction and a nuisance", which confuses students and "it would be better if it didn't appear" (not my words, but @cboettig's above). [Two](https://github.com/rocker-org/devcontainer-templates/issues/28) [users](https://github.com/rocker-org/rocker-versioned2/issues/731) already opened an issue, [two more](https://github.com/rocker-org/rocker-versioned2/issues/135) mention it here, and another bothered to write a [blog post](https://notes.rmhogervorst.nl/post/2020/09/23/solving-libxt-so-6-cannot-open-shared-object-in-grdevices-grsoftversion/).
2. The missing lib [breaks x11 support](https://github.com/rocker-org/rocker-versioned2/issues/731#issuecomment-1866650250).
3. One possible solution, i.e. building R without x11, [is not an option](https://github.com/rocker-org/rocker-versioned2/issues/731#issuecomment-1868173298).
4. Another solution is to add libxt6 to the r-ver (et al) image(s). According to my tests, adding libxt6 to the image increases its size by a factor of less than 0.001 (I count 0.67 MB, see [also](https://packages.ubuntu.com/jammy/libxt6), while r-ver clocks in at 800+ MB). That's negligible, isn't it?  

When I look at 1 and 4 this all seems like an easy fix to me. Nevertheless I sense reluctance to fix it like that (or at all), which I don't understand. Nor how the warning can be considered a [feature, not a bug](https://github.com/rocker-org/devcontainer-templates/issues/28#issuecomment-1895958457).

What am I missing?

Another aside: If image size really is a priority, I'd suggest using [`autopurge`](https://manpages.debian.org/unstable/apt/apt-get.8.de.html) instead of [`autoremove`](https://github.com/rocker-org/rocker-versioned2/blob/f0ad63ba5b49768c3c333b8d4a54b3122b830aa6/scripts/install_R_source.sh#L161) (without `--purge`). This reduces the image size by 0.84 MB, i.e. by more than what libxt6 would add.

**Closed** 2024-01-18 17:49 UTC
Labels: bug

**Comment by benz0li** [comment] 2024-01-19 09:39
Well... [`libtcl8.6`](https://packages.ubuntu.com/jammy/libtcl8.6) and [`libtk8.6`](https://packages.ubuntu.com/jammy/libtk8.6) *should* also be installed, then:

```bash
root@7519de4b9c2e:/usr/local/lib/R# ldd /usr/local/lib/R/library/tcltk/libs/tcltk.so
	linux-vdso.so.1 (0x00007fff3a141000)
	libtcl8.6.so => not found
	libtk8.6.so => not found
	libR.so => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f14f7e72000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f14f80ac000)
```

**Comment by benz0li** [comment] 2024-01-19 09:42
IMHO The X11-functionality demonstrated with the `rocker/r-base` image in https://github.com/rocker-org/rocker-versioned2/issues/731#issuecomment-1866650250 is only going to work with `rocker/r-ver` if [`xauth`](https://packages.ubuntu.com/jammy/xauth) is installed, too.

([`r-base`](https://packages.ubuntu.com/jammy/r-base), i.e. [`r-base-core`](https://packages.ubuntu.com/jammy/r-base-core), installs [`xdg-utils`](https://packages.ubuntu.com/jammy/xdg-utils) in addition)
