### ISSUE TITLE
tidyverse image without Rstudio dependency

### ISSUE THREAD

**Issue by Fredo-XVII** [rocker-org/rocker-versioned2#315] opened 2022-01-04 20:43 UTC
Hello! 

I was looking at upgrading my docker at work from 3.6.3 to 4.x.x and I was wondering if there was a way to set up the docker for R and tidyverse without the Rstudio dependency?  Rstudio makes the image very large and I do not need or use it for the work that I do.  One reason is that we cannot log into the container were the image will run for security reasons.  I debug the code using kibana logs.

One other reason to remove Rstudio is to avoid the errors with passing a password to log in to RStudio.  This creates an error every now and then, and the solution is to just rebuild the container.  But this is a bad solution.

I found the tidyverse image build below @: https://github.com/rocker-org/rocker-versioned2/blob/master/dockerfiles/tidyverse_4.0.2.Dockerfile

Here is a copy of the code at the above location:

```
FROM rocker/rstudio:4.0.2

LABEL org.opencontainers.image.licenses="GPL-2.0-or-later" \
      org.opencontainers.image.source="https://github.com/rocker-org/rocker-versioned2" \
      org.opencontainers.image.vendor="Rocker Project" \
      org.opencontainers.image.authors="Carl Boettiger <cboettig@ropensci.org>"

RUN /rocker_scripts/install_tidyverse.sh
```

What I want to know if I can replace the `FROM` statement with `FROM rocker/r-ver:4.1.2` from the base image? Like so:

```
FROM rocker/r-ver:4.1.2

LABEL org.opencontainers.image.licenses="GPL-2.0-or-later" \
      org.opencontainers.image.source="https://github.com/rocker-org/rocker-versioned2" \
      org.opencontainers.image.vendor="Rocker Project" \
      org.opencontainers.image.authors="Carl Boettiger <cboettig@ropensci.org>"

RUN /rocker_scripts/install_tidyverse.sh
```

Thanks for the help!!

**Comment by cboettig** [comment] 2022-01-04 21:21
yup, the Dockerfile recipe you have above *should* work, though we may still need to copy over some of the apt dependencies that get added in the `rocker_scripts/install_rstudio.sh` to also be in `install_tidyverse.sh` to be safe.  (You'll find these scripts in the `scripts/` dir of this repo).  

I don't quite follow the point about 
> One other reason to remove Rstudio is to avoid the errors with passing a password to log in to RStudio. This creates an error every now and then, and the solution is to just rebuild the container. But this is a bad solution.

If you aren't using RStudio, there's no reason to mess around with passwords.  Something like:

```
docker run --rm -ti rocker/tidyverse R
```

should drop you into a CLI R session no problem.  (Of course you may want to adjust that to bind local volumes, login as the `rstudio` user instead of root user, run Rscript or a bash shell instead of R cli, or whatever you need).  

Hope this helps.

**Comment by Fredo-XVII** [comment] 2022-01-04 21:42
In regards to your question about Rstudio password, it is similar to the issue: https://github.com/rocker-org/rocker/issues/303

I was getting this error below:
```
ERROR: You must set a unique PASSWORD first!! e.g. run with:
docker run -e PASSWORD=<YOUR_PASS> -p 8787:8787 rocker/rstudio
```
Nothing that I tried to do to fix it worked.  I just kept getting the error.  For what ever reason if I made changes to the docker file and rebuilt the image, and built a new container I would then get the message above again.  So I would rebuilt the new container a second time to get passed this error.  It was weird behavior.  

And using this code didn't work to by pass the error:  `docker run --rm -p 127.0.0.1:8787:8787 -e DISABLE_AUTH=true rocker/rstudio`

`-ti` won't help me.  Our docker images are pushed to a kubernetes cluster, which builds and runs the container, and we are not allowed to CLI into those containers.  So you have to test it on a different platform and figure out from the kibana logs if there are any errors.

As for the tidyverse image, you got it.  That was my concern that something would be missing going from base version to tidyverse and bypassing Rstudio .sh script.

When I go to upgrade, I will add those apt dependencies.  Is there a reason that rocker-org doesn't provide a stand alone tidyverse dockerfile?

Thanks for the help!!!

**Comment by eddelbuettel** [comment] 2022-01-04 21:55
[ It's not entirely clear to me if you wanrt a 'versioned' stack (near and dear to Carl) or just the working set of tidyverse packages. If it is the latter, just pull in rocker/r-bspm:20.04 and run `install.packages("tidyverse")` and you will get _all binaries_ that install in about a minute or two (held back mostly by network and disk speed).  I have demo gifs on my website as part of some blog posts ...  ]

**Comment by cboettig** [comment] 2022-01-05 00:32
@Fredo-XVII I really suggest you copy-paste the code I provided for starters, it provides a simple reproducible example of running an alternative default command, such as the R cli.  You are quite correct that in all the examples you show you are not providing an alternative run command (which follows after the image name), and thus you are merely getting the default run command, which is to launch the RStudio server.  Since you're not planning to use RStudio server, you do not need a port or a password, just literally run `docker run --rm -ti rocker/tidyverse R` to drop into command-line R.  please consult the standard docker documentation or our website, https://rocker-project.org, for more details.

We provide a limited number of Dockerfiles because rocker already has quite a large number of different images (over a dozen) and tags (100s).  Too many different options becomes difficult for users to navigate to discover the precise combination they want.  It's better for users to just add the packages they need, which is pretty straight forward in most cases as noted in either option above.

**Comment by eitsupi** [comment] 2022-01-05 01:08
FYI, from my experience of doing some testing for arm64 adaptation, the following Dockerfile will work.

```Dockerfile
FROM rocker/r-ver:4.1.2
RUN /rocker_scripts/install_tidyverse.sh
```

(Note that, the above Dockerfile will not work on arm64 because it lacks cmake to build Apache Arrow https://github.com/apache/arrow/pull/11703, but it can be built on arm64 if cmake is installed separately. Until the `install2.r` command was updated recently, the build did not fail even if `arrow` was not installed, so I did not realize until recently that cmake dependency is required.)

**Comment by eddelbuettel** [comment] 2022-01-05 01:28
(Sure.  Note that I was showing an R command from an already made container, alleviating even the need to create a new container.  But @cboettig is spot on, this seems a little like a usage error ...  Suggest we close this.)

**Closed** 2022-01-06 20:27 UTC

**Comment by Fredo-XVII** [comment] 2022-01-17 18:14
Hello! 

Sorry, been dealing with lots of stuff so I couldn't reply right away.  First, thank you all for your suggestions.

To @eddelbuettel, what I have found is that when I use the base version and `install` tidyverse, that rJava/Java doesn't work very well and I have issues with making connections across the network.  So the base R image + `install.packages('tidyverse') is not a solution for me.  I don't need all the packages in tidyverse.  For example, I have no use for ggplot2 in my current process.  I am just using the Rstudio image for its dependencies, and that is built on top of the tidyverse image.  

For what ever reason, the Rstudio image does solve my JAVA problems and allows me to do just everything that I need to do.  I don't need Rstudio, however, for anything that I am doing.  What I would like is an image with the Rstudio dependencies, but without Rstudio.  Its the architecture that I am after.

I apologize, my question is a little confusing; I should have been more clear.  But you are correct that you can't do an image that is customized for everyone. 

@cboettig Thanks for ideas! I will test them to see what I get. 

Again, sorry for the late response.

**Comment by eddelbuettel** [comment] 2022-01-17 18:21
Well as the Debian maintainer of package `r-cran-rjava`, _i.e._ the Debian packaging of CRAN package `rJava` for well over a decade I can assure that if you actually use the binary package offered via `apt` and friends it generally works. From what I can tell breakage happens when folks ignore the existence of that package (and its dependencies), try things by hand and more often than not end up in tears.

**Comment by Fredo-XVII** [comment] 2022-01-17 20:00
The rJava package is not the issue; I was just describing my pain point with getting R to work on Linux.  It is getting the dependencies right for Linux that I feel I had trouble with.  Even installing openJDK I had issues with the getting JAVA to work on linux with the base R image.  It was only with the Rstudio image, and its Linux dependencies, that I was able to get it working.

I am not a CS guy and I dabble with Linux only because of Docker.  

Thanks for all the work that you do! `littler` save me from a bunch of headaches getting packages installed on Linux.

**Comment by eddelbuettel** [comment] 2022-01-17 20:14
It can be very straightforward if you know where to look, what to learn
- I have provided what is behind `sudo apt install r-base` for 20+ years; that gives you R
- This particular flavour gives you binaries even if you say `install.packages()` but I don't use that here
- Similarly you can add rJava, or have it added as a dependency
- I don't like or use Java much but I had to _eg_ rely on XLConnect before we got openxlsx.

Here is a truly minimal one command demo.  It uses Ubuntu because we have a PPA with over 5000 binaries for CRAN (but there are alternative).  I start the container, update the `apt` index and install it:

```sh
edd@rob:~$ docker run --rm -ti rocker/r-bspm:20.04 bash
root@e33b16321b40:/# apt update -qq
25 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@e33b16321b40:/# apt install r-cran-xlconnect 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  ca-certificates-java default-jre default-jre-headless java-common libasound2 libasound2-data libavahi-client3 libavahi-common-data libavahi-common3 libcups2 libdrm-amdgpu1 libdrm-common libdrm-intel1
  libdrm-nouveau2 libdrm-radeon1 libdrm2 libedit2 libgif7 libgl1 libgl1-mesa-dri libglapi-mesa libglvnd0 libglx-mesa0 libglx0 liblcms2-2 libllvm12 libnspr4 libnss3 libpciaccess0 libpcsclite1 libsensors-config
  libsensors5 libvulkan1 libx11-xcb1 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-sync1 libxcb-xfixes0 libxfixes3 libxi6 libxshmfence1 libxtst6 libxxf86vm1 openjdk-11-jre
  openjdk-11-jre-headless r-cran-rjava
Suggested packages:
  libasound2-plugins alsa-utils cups-common liblcms2-utils pciutils pcscd lm-sensors libnss-mdns fonts-dejavu-extra fonts-ipafont-gothic fonts-ipafont-mincho fonts-wqy-microhei | fonts-wqy-zenhei fonts-indic
Recommended packages:
  alsa-ucm-conf alsa-topology-conf mesa-vulkan-drivers | vulkan-icd libatk-wrapper-java-jni fonts-dejavu-extra
The following NEW packages will be installed:
  ca-certificates-java default-jre default-jre-headless java-common libasound2 libasound2-data libavahi-client3 libavahi-common-data libavahi-common3 libcups2 libdrm-amdgpu1 libdrm-common libdrm-intel1
  libdrm-nouveau2 libdrm-radeon1 libdrm2 libedit2 libgif7 libgl1 libgl1-mesa-dri libglapi-mesa libglvnd0 libglx-mesa0 libglx0 liblcms2-2 libllvm12 libnspr4 libnss3 libpciaccess0 libpcsclite1 libsensors-config
  libsensors5 libvulkan1 libx11-xcb1 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-sync1 libxcb-xfixes0 libxfixes3 libxi6 libxshmfence1 libxtst6 libxxf86vm1 openjdk-11-jre
  openjdk-11-jre-headless r-cran-rjava r-cran-xlconnect
0 upgraded, 49 newly installed, 0 to remove and 25 not upgraded.
Need to get 72.2 MB of archives.
After this operation, 620 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
```

After saying 'Y' here and waiting maybe be a minute or less (I have decent broadband):

```sh
root@e33b16321b40:/# R

R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

Loading required package: utils
Tracing function "install.packages" in package "utils"
> library(XLConnect)
XLConnect: It seems downloading the JAR dependencies may have failed. If you would like to use a different maven repository, please set the environment variable XLCONNECT_JAVA_REPO_URL to a valid URL, e.g. Sys.setenv(XLCONNECT_JAVA_REPO_URL='https://jcenter.bintray.com'), and reinstall the package.
XLConnect 1.0.4 by Mirai Solutions GmbH [aut],
  Martin Studer [cre],
  The Apache Software Foundation [ctb, cph] (Apache POI),
  Graph Builder [ctb, cph] (Curvesapi Java library),
  Brett Woolridge [ctb, cph] (SparseBitSet Java library)
https://mirai-solutions.ch
https://github.com/miraisolutions/xlconnect
> 
```

So the Java-using package loads as expected.  No issue.  Fully automatic.  And it worked this way for 13+ years.

**Comment by Fredo-XVII** [comment] 2022-01-17 21:21
Wow! That is really cool!  It takes like 16 minutes on average to get my in house package built because it is builds all the dependencies from source.  I am not a fan of JAVA either; it changes my data types when I pull data.  At work, all of our systems talk to each other with JAVA pretty easily, and I would be the outlier building stuff with ODBC.  I prefer ODBC, but that is a pain on Linux.

I am very excited about this because if I can get my build time down, that would be so productive.  Would this work for Debian? At work, I believe Vela builds on Debian v10.

Thanks again for the tips!!

**Comment by eddelbuettel** [comment] 2022-01-17 22:05
`r-cran-rjava` is for sure in Debian.  And Debian testing has around 1000 `r-cran-*` packages.  You can always search via `apt-cache search r-cran-foo` (with foo the term you are after) or at https://packages.debian.org/foo if foo is the source package name. There is also a searchable interface at that website.  And there is the `r-sig-debian` mailing list.

And yes, binaries are way faster to install :)  I have been beating that drum for a few years on my blog ...

**Comment by Fredo-XVII** [comment] 2022-01-17 22:22
This is great! Thank you @eddelbuettel !!
