### ISSUE TITLE
Change the Shiny Server UID to access bind mounted volumes

### ISSUE THREAD

**Issue by vincentvanhees** [rocker-org/rocker-versioned2#341] opened 2022-01-27 09:21 UTC
I am trying to create a rocker/shiny-based container with a shiny app that writes to a mounted volume. I tried to follow your wiki instructions on [Sharing files ...](https://github.com/rocker-org/rocker/wiki/Sharing-files-with-host-machine) and [How to save...](https://github.com/rocker-org/rocker/wiki/How-to-save-data), but without much luck.

Yesterday I created [this](https://community.rstudio.com/t/writing-to-mounted-volume-by-shiny-app-from-inside-docker-container-app-crashes/127438) post in RStudio community. But I am not sure now whether I should have posted it here...

Sorry for double posting, but I really would like to get this to work. I can pay for a couple of hours of consultancy to whoever is able to resolve this seemingly simple problem.

**Comment by vincentvanhees** [comment] 2022-01-28 12:04
I would like my Shiny app to have write/read permissions for a directory on the host, but also that the user of the Shiny app can have full control over the created files.

The project I am working on is https://github.com/habitus-eu/HabitusGUI, which in short aims to let researchers process their research data by running the docker container with the Shiny app as the GUI. The container takes 15 minutes or so to build, which is why I am now debugging the issue with [this](https://github.com/vincentvanhees/rshiny_in_docker_test) simple test repo, which takes less than a minute to build.

As the code is intended for use by others it would be nice if it could remain easily adaptable to new users with potentially different directory paths on the host.

**Comment by vincentvanhees** [comment] 2022-02-21 13:17
If I understand correctly docker volume expects me to copy all my data to the folder associated with the newly created volume. This is not ideal because that would involve having to copy terabytes of data. The most intuitive solution to me would be to leave the data where it is and to tell the docker image where to find them via bind mount. 

However, I am struggling to find a way to allow the shiny app to write to the mounted volume in a way that the user can still read/edit the files. 

It would be helpful if there was a demo repository with shiny code, Dockerfile, and docker commands to showcase how to let a docker image interact with mounted volumes. That is why I started with https://github.com/vincentvanhees/rshiny_in_docker_test as minimalistic test case but unfortunately I am not getting it to work.

**Comment by eitsupi** [comment] 2022-02-21 13:55
You may be able to change the UID and GID of shiny user this way. https://github.com/rocker-org/rocker-versioned2/issues/355#issuecomment-811860319

**Comment by eitsupi** [comment] 2022-04-02 09:01
Duplicate of #355

**Closed** 2022-04-02 09:01 UTC
Labels: duplicate, enhancement
