### ISSUE TITLE
Flaky focal/latest in CRAN url

### ISSUE THREAD

**Issue by Skenvy** [rocker-org/rocker-versioned2#547] opened 2022-09-25 10:59 UTC
### Container image name

rocker/tidyverse:4.2.1

### Container image digest

rocker/tidyverse@sha256:ac29eda66c85a375537165763a88c8c98149e25adef9d0dfea1571bc3dbf72c2

### What operating system are you seeing the problem on?

Linux

### System information

- Docker version 1.41
- OS Ubuntu 20.04.5 (`ubuntu-latest` in gh-actions at the time of writing.)
- R CMD check version
  - using R version 4.2.1 (2022-06-23)
  - using platform: x86_64-pc-linux-gnu (64-bit)
  - using session charset: UTF-8
  - using option ‘--as-cran’

### Bug description

Doing an `R CMD check --as-cran` with the mentioned image uses the CRAN url from the r-ver:4.2.1 dependent image, `https://packagemanager.rstudio.com/cran/__linux__/focal/latest`, which causes the `--as-cran` flag to periodically fail with the message;
```
cannot open URL 'https://packagemanager.rstudio.com/cran/__linux__/focal/latest/src/contrib/Meta/current.rds': HTTP status was '404 Not Found'
```

Additionally potentially relevant information is that this started to occur in tandem with updating the `r-lib/actions` in some workflows (which pull and run commands in the tidyverse container), with the diff between the old and new workflow versions being https://github.com/r-lib/actions/compare/43e2714071e44b1e373b83e7374dbc39e8b04f55..cc43801a5c7c7730c2bb132cc3b245281df03764

### How to reproduce this bug?

```sh
The command `R CMD check --as-cran <tarball>` being run as a step in the workflow job that uses the image.

Issue was found on https://github.com/Skenvy/Collatz/blob/986020aede2038fba23e0ab111fa340c4eba0513/.github/workflows/R-test.yaml#L83 before 4.2.1 was changed to 4.2.0 which fixed the issue.
```

**Comment by eitsupi** [comment] 2022-09-25 11:04
Thank you for reporting this.
However, this is a duplicate of #532.

Could you report `r-lib/actions`'s problems to that repository?

**Closed by eitsupi** 2022-09-25 11:04 UTC
Labels: bug
