### ISSUE TITLE
libtk8.6.so not installed

### ISSUE THREAD

**Issue by MechantRouquin** [rocker-org/rocker-versioned2#707] opened 2023-09-28 12:41 UTC
### Container image name

rocker:r-ver

### Container image digest

rocker:r-ver:4.2.3

### What operating system related to this question?

Linux

### System information

- Docker version 24.0.6
- Linux Mint 20.3 

### Question

I would like to know if the __libtk8.6.so__ used by the base package __tcltk__ isn't installed due to docker size purpose ?

I try to install a package {soiltexture}, who depend of {tcltk}, from source on rocker/r-ver:4.x.x but libtk8.6.so is not installed on this base image and prevents the installation of the package {soiltexture}.

The {tcltk} library linkage :    
```bash
ldd /usr/local/lib/R/library/tcltk/libs

        linux-vdso.so.1 (0x00007fffc24ca000)
	libtcl8.6.so => not found
	libtk8.6.so => not found
	libR.so => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe1616a7000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe1618ac000)
```

My error :   
```bash
  error: unable to load shared object '/usr/local/lib/R/library/tcltk/libs/tcltk.so':
  libtcl8.6.so: cannot open shared object file: No such file or directory
```

After  
```bash
apt-get install libtk8.6
```

Everythings is fine !

Is this intended or is this a bug ?

Thank you

**Comment by eitsupi** [comment] 2023-09-28 12:45
Maybe duplicate of #268

@cboettig Any thoughts?

**Comment by eitsupi** [comment] 2023-09-28 13:14
> By the way apt-get understand libtk as libtk8.6 (or other versions), it's easier to maintain in the dockerfile.

Good information. I don't think we knew that.

**Comment by eitsupi** [comment] 2023-10-04 13:26
@cboettig Could you take a look at this?

**Comment by benz0li** [comment] 2023-10-04 18:09
Package `soiltexture` imports `sp` which is installed in the `rocker/geospatial`. This image also has linux packages `tk-dev` (and `tcl-dev`) installed.  
👉 @MechantRouquin I recommend using the `rocker/geospatial` image.

**Comment by benz0li** [comment] 2023-10-04 18:11
@eitsupi Regarding the `sp` package:

```R
> library(sp)
The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
which was just loaded, were retired in October 2023.
Please refer to R-spatial evolution reports for details, especially
https://r-spatial.org/r/2023/05/15/evolution4.html.
It may be desirable to make the sf package available;
package maintainers should consider adding sf to Suggests:.
```

**Comment by cboettig** [comment] 2023-10-04 20:44
I don't think libtk is relevant to the base image.  Yes base R is compiled against those dev libraries, but I think mostly for GUI interfaces in base R that will not work in either the bash command line (without binding an X window system) or in RStudio.  

Yes, libtk is in `rocker/geospatial` and users can use that or add libtk like they would any other dev lib we don't bundle in the stack.  (as OP notes above.  It has never been the intent of rocker to include every dev library bound by some R package in CRAN in the base image, that would indeed make the image huge for no particularly good reason).  

I generally think package developers should no longer assume that the TCL/TK GUI is the most convenient / portable way to add a GUI interface to an R package.  Many older packages did this when it used to be a more reasonable assumption (like `sp`), and yes, some such packages are slated for deprecation (like `sp`).

**Closed by cboettig** 2023-10-04 20:44 UTC
Labels: question
