### ISSUE TITLE
Operation Not Permitted Error from Rocker RStudio Image on M1 MacBook

### ISSUE THREAD

**Issue by kuang-da** [rocker-org/rocker-versioned2#287] opened 2021-11-17 02:37 UTC
Hi,

I try to run the following command to have the RStudio Server run on an M1 MacBook with macOS Monterey. 

```
docker run -e PASSWORD=yourpassword --rm -p 8788:8787 rocker/rstudio
```

But I keep having the following error after the login page. 

```
[rserver] ERROR system error 1 (Operation not permitted); OCCURRED AT rstudio::core::Error rstudio::core::system::posix::{anonymous}::restorePrivilegesImpl(uid_t) src/cpp/shared_core/system/PosixSystem.cpp:66; LOGGED FROM: rstudio::core::Error rstudio::core::system::launchChildProcess(std::__cxx11::string, std::__cxx11::string, rstudio::core::system::ProcessConfig, rstudio::core::system::ProcessConfigFilter, PidType*) src/cpp/core/system/PosixSystem.cpp:2168
```

Any suggestions would be highly appreciated. Thank you very much!

**Comment by eitsupi** [comment] 2021-11-17 06:53
It seems duplicate of #144.
RStduio Server does not support arm64 architecture at this time. Therefore, RStduio Server does not seem to work on M1 mac.

**Comment by echuber2** [comment] 2021-12-28 13:59
Perhaps the x86 version will work with the latest version of Docker Desktop for Mac if Rosetta 2 emulation for amd64 architecture is enabled. Details are explained here: https://docs.docker.com/desktop/mac/apple-silicon/ I can't test this myself either.

**Comment by gaojunxuan** [comment] 2022-01-10 08:29
> Perhaps the x86 version will work with the latest version of Docker Desktop for Mac if Rosetta 2 emulation for amd64 architecture is enabled. Details are explained here: https://docs.docker.com/desktop/mac/apple-silicon/ I can't test this myself either.

Unfortunately, this does not seem to work.

**Comment by echuber2** [comment] 2022-01-10 23:34
I see, that's unfortunate. I heard one report of someone getting the PrairieLearn version of Rocker to work locally on an M1 Mac, so maybe you'd like to try that version, but it may not be configured for your needs:

https://github.com/PrairieLearn/PrairieLearn/tree/master/workspaces/rstudio

**Comment by gaojunxuan** [comment] 2022-01-11 05:10
> I see, that's unfortunate. I heard one report of someone getting the PrairieLearn version of Rocker to work locally on an M1 Mac, so maybe you'd like to try that version, but it may not be configured for your needs:
> 
> https://github.com/PrairieLearn/PrairieLearn/tree/master/workspaces/rstudio

Do you have any detail or link to that report and/or a working example?

**Comment by eddelbuettel** [comment] 2022-01-11 13:43
I had verbal confirmation from @barbehenna works with me on things involving quite a bit of docker that this worked on his new M1 macbook. Standard launch of Docker in daemon mode to have RStudio exposed via the network as usual.  

All this ... surprised me which is why I brought it up to @echuber2 who help us here / essentially built and tweaked this thing for our use in the test and grade software we use.  @echuber2 may know best what the delta is to upstream -- we lifted on authentication step not needed in our setup as I recall, and added (iirc) one `nginx` indirection needed for us.  I do not see how that makes the difference so maybe some digging will reveal it.  

I am still confused as to how this can have worked when it didn't for everybody else.

**Comment by echuber2** [comment] 2022-01-11 19:41
@gaojunxuan Can you try out this script on your Mac? Supposedly, this works with macOS Monterey 12.1 on an M1 Pro. Docker version 20.10.11, Docker Desktop 4.3.2. Thanks to @barbehenna for testing this.

https://gist.github.com/echuber2/2dd51ab799411cbd4894f8a85a3db52c

**Comment by gaojunxuan** [comment] 2022-01-11 20:19
> @gaojunxuan Can you try out this script on your Mac? Supposedly, this works with macOS Monterey 12.1 on an M1 Pro. Docker version 20.10.11, Docker Desktop 4.3.2. Thanks to @barbehenna for testing this.
> 
> https://gist.github.com/echuber2/2dd51ab799411cbd4894f8a85a3db52c

Yes! This works. I have not tried all the features yet, but at least RStudio seems to work fine. I wonder if it is because of some file/folder permission issue as the "Operation not permitted" error message I got when trying to use the vanilla Rocker image seems it was trying to modify some permission settings and failed.
```
11 Jan 2022 19:30:40 [rserver] ERROR system error 1 (Operation not permitted); OCCURRED AT.
rstudio::core::Error rstudio::core::system::posix::{anonymous}::restorePrivilegesImpl(uid_t) 
src/cpp/shared_core/system/PosixSystem.cpp:66; LOGGED FROM: void rstudio::server::pam_auth::
{anonymous}::assumeRootPriv() src/cpp/server/ServerPAMAuth.cpp:57

11 Jan 2022 19:30:41 [rserver] ERROR system error 1 (Operation not permitted); OCCURRED AT 
rstudio::core::Error rstudio::core::system::posix::{anonymous}::restorePrivilegesImpl(uid_t) 
src/cpp/shared_core/system/PosixSystem.cpp:66; LOGGED FROM: rstudio::core::Error 
rstudio::core::system::launchChildProcess(std::__cxx11::string, std::__cxx11::string, 
rstudio::core::system::ProcessConfig, rstudio::core::system::ProcessConfigFilter, PidType*) 
src/cpp/core/system/PosixSystem.cpp:210
```

**Comment by echuber2** [comment] 2022-01-11 20:24
Interesting, thanks a lot for trying it. The PrairieLearn version is set up to run as a non-root user. I'm still not sure why the default version of Rocker works with non-M1 chips by default, if this is the issue. Maybe it's not an ARM issue _per se_ but a difference in how the M1 kernels handle permissions.

**Comment by eitsupi** [comment] 2022-06-06 03:16
Duplicate of #144

**Closed by eitsupi** 2022-06-06 03:16 UTC
Labels: bug, help wanted, needs more info
