### ISSUE TITLE
Issue with 4.1.1 rocker/rstudio

### ISSUE THREAD

**Issue by ChaitDevOps** [rocker-org/rocker-versioned2#345] opened 2022-02-07 20:40 UTC
Hello - I'm using rocker/rstudio (tag 4.1.1) and my users are seeing this error on the r console. This just started happening without any change in the env. I've since re-installed "rJava" package along with all the other rstudio packages and error keeps appearing. 
Please see below java version of the container.

what's strange is that this error is not constant. It keeps changing. Sometimes i get the `recursive gc invocation` error and it hangs for a while and crashed rstudio. Can someone please advise me on how to approach this problem?

```
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.13+8-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```

```r
> library(DBI)
> library(rJava)
Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: FUN(X[[i]], ...)
  error: no such symbol PushToREXP in package rJava
> library(RJDBC)
Loading required package: rJava
Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: FUN(X[[i]], ...)
  error: no such symbol PushToREXP in package rJava
Error: package ‘rJava’ could not be loaded
> options(java.parameters = "-Xmx8048m") #This is necessary to be able to load large amounts of data via RJDBC
> library(mailR)
Error: package or namespace load failed for ‘mailR’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: FUN(X[[i]], ...)
  error: no such symbol PushToREXP in package rJava
> library(tictoc)
> library(tidyverse)
Error: package or namespace load failed for ‘tidyverse’:
 .onLoad failed in loadNamespace() for 'fansi', details:
  call: options()
  error: Value of SET_STRING_ELT() must be a 'CHARSXP' not a 'NULL'
```

**Comment by cboettig** [comment] 2022-02-08 22:37
Installing additional packages often requires the use of additional external libraries.  We know this can be tricky, which is why we provide a few different ways to help.  I strongly suggest you try using the `rocker/verse` image instead of the `rocker/rstudio` image -- it is the same as the `rocker/rstudio` image except that it already installs the additional dependencies required for tidyverse and rJava packages:

Example: run this code:

```
docker run --rm -ti rocker/verse:4.1.1 R -e "library(rJava)"
```

produces:

```
R version 4.1.1 (2021-08-10) -- "Kick Things"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(rJava)
> 
> 
```

note that here rJava loads without error.  


Just a footnote that I cannot reproduce the error you describe above because you haven't documented how you've installed rJava or other necessary details about your runtime configuration.  Please try copy-pasting the example `docker run` command provided above to verify if that reproduces the same successful R environment as I'm seeing.

**Comment by ChaitDevOps** [comment] 2022-02-09 01:12
Hi Carl - Thanks for your response. Here is how i install all the packages. I create a mini  local repo and then install packages from that repo. I have "rjava" also included in the package list.  `RUN Rscript /tmp/install_or_die.R`.  In my Dockerfile, I also have a section for installing OS dependent packages. pls see below

For the `rocker/verse` image, is there a list of packages somewhere that come pre-installed? Thanks again for your help. really appreciate it.

install_or_die.R
```
library("miniCRAN")
revolution <- c(CRAN = "https://cran.microsoft.com")
pkgs <- c("large-package-list")
pkgList <- pkgDep(pkgs, repos = revolution, type = "source")
write("TMPDIR = '/tmp'", file=file.path(Sys.getenv('R_USER'), '.Renviron'))
dir.create(pth <- file.path(tempdir(), "miniCRAN"))
makeRepo(pkgList, path = pth, repos = revolution, type = "source")
install.packages(pkgs, repos = paste0("file:///", pth), type = "source", INSTALL_opts="--no-multiarch")
```

Dockerfile
```
RUN apt-get update -y && \
    apt-get install -y libc6-dev libxml2 libglpk-dev libudunits2-dev default-jdk tk8.6-dev && \
    apt-get install -y cargo libv8-dev libwebp-dev libgmp3-dev libsodium-dev libpoppler-cpp-dev git wget zip unzip openssh-server unixodbc-dev supervisor && \
    apt-get install -y odbc-postgresql cron
```

**Comment by cboettig** [comment] 2022-02-09 01:36
yeah things are a bit cryptic in our new build system.  The [dockerfiles](https://github.com/rocker-org/rocker-versioned2/tree/master/dockerfiles) are a good reference, as you can see from them, `rocker/verse` builds on `rocker/tidyverse`, which builds on `rocker/rstudio`.  The install scripts are the best place to see what each one adds:

- [install_tidyverse.sh](https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/install_tidyverse.sh), 
- [install_verse](https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/install_verse.sh)

All the install scripts from the `scripts` directory are placed on every versioned image, inside `/rocker_scripts`, so these could easily be invoked on any derivative images (the intent is that these are 'stand-alone' so you could, say, add the geospatial stack without adding rstudio, for instance, though that's not fully tested since the pre-built images stack these up pretty linearly).  

HTH

**Comment by eitsupi** [comment] 2022-02-09 02:13
> For the rocker/verse image, is there a list of packages somewhere that come pre-installed?

See the wiki https://github.com/rocker-org/rocker-versioned2/wiki

**Comment by eitsupi** [comment] 2022-04-02 08:54
I would like to close this issue due to lack of updates. If you have additional information about the issue, please do not bother to reopen it.

**Closed by eitsupi** 2022-04-02 08:54 UTC
Labels: needs more info
