### ISSUE TITLE
Singularity container ERROR system error 11 (Resource temporarily unavailable)

### ISSUE THREAD

**Issue by kubu4** [rocker-org/rocker-versioned2#150] opened 2021-04-21 18:45 UTC
I've followed the [Rocker Singularity install instructions](https://www.rocker-project.org/use/singularity/):

```shell
singularity pull --name rstudio.simg docker://rocker/rstudio:latest
singularity exec rstudio.simg rserver --www-address=127.0.0.1
```

When I go to the address (`127.0.0.1:8787`) in my web browser, it triggers the following error:

```
21 Apr 2021 18:23:23 [rserver] ERROR database error 7 (sqlite3_statement_backend::loadOne: attempt to write a readonly database)
[description: Could not delete expired revoked cookies from the database, description: 
Could not read revoked cookies from the database];
OCCURRED AT virtual rstudio::core::Error rstudio::core::database::Connection::execute(rstudio::core::database::Query&, bool*)
src/cpp/core/Database.cpp:480; LOGGED FROM: int main(int, char* const*) src/cpp/server/ServerMain.cpp:729
```

This appears to be the same problem described in #109 . That issue was resolved by using `rocker/rstudio:4.0.2`. 

I did that:

```shell
singularity pull --name rstudio-4.0.2-clean.simg docker://rocker/rstudio:4.0.2
singularity exec rstudio-4.0.2-clean.simg rserver --www-address=127.0.0.1
```

When  I enter `127.0.0.1:8787` in my web browser, a different error gets thrown:

```
21 Apr 2021 18:29:24 [rserver] ERROR system error 11 (Resource temporarily unavailable)
[description: Could not acquire revocation list file lock];
OCCURRED AT rstudio::core::Error rstudio::server::auth::handler::initialize() src/cpp/server/auth/ServerAuthHandler.cpp:569;
LOGGED FROM: int main(int, char* const*) src/cpp/server/ServerMain.cpp:674
```

Singularity version: 3.7.3

It seemed like this should be so simple, based on the [Rocker Singularity install instructions](https://www.rocker-project.org/use/singularity/). 

I'm not well versed in using Singularity/containers, so am not really sure what to try. Any suggestions/insight would be much appreciated.

**Comment by eitsupi** [comment] 2021-05-08 09:56
I don't understand anything about Singularity, but is this the same as this issue https://github.com/rocker-org/rocker/issues/456?

That issue seems to be solved by this comment. https://github.com/rocker-org/rocker-versioned2/issues/105#issuecomment-799848638

**Comment by eitsupi** [comment] 2022-06-04 15:39
Duplicate of #105

**Closed by eitsupi** 2022-06-04 15:39 UTC
Labels: duplicate, question
