### ISSUE TITLE
[Singularity] RStudio 2021.09 or later does not launch

### ISSUE THREAD

**Issue by ryao-mdanderson** [rocker-org/rocker-versioned2#474] opened 2022-06-01 14:25 UTC
Dear rocker team:
  I usually use singularity pull an rstudio container from docker hub, and launch the sif image on HPC cluster, we use LSF scheduler. It works well for 4.1.0 and older. My recent work with rstudio 4.2.0 hit a rock:
  singularity pull docker://rocker/rstudio:4.2.0, then I tried to launch this rstudio_4.2.0.sif using a similar script that works with version 4.1.0, it does not launch, and there is no error message logged except the exit code 1. 
 May you please direct me an example that works with singularity for rstudio 4.2.0 on HPC cluster, if possible?

Thank you very much.

**Comment by eitsupi** [comment] 2022-06-01 14:29
#105 may help you.

**Comment by ryao-mdanderson** [comment] 2022-06-01 15:15
@eitsupi Thanks for reply.
I read #105, some solutions we have applied to rstudio version 4.1.0 earlier. I am luck to have 4.1.0 works well, however, I am now stuck on launching 4.2.0 singularity image. Thanks for help.

**Comment by ryao-mdanderson** [comment] 2022-06-02 04:32
@eitsupi : I tested rocker/rstudio:4.1.1 4.1.2 4.1.3 and 4.2.0 all 4 versions can't be launched by singularity. 
my working version is 4.1.0. 
Thank you for your time to support this.

**Comment by eitsupi** [comment] 2022-06-02 11:08
It seems RStudio Server 2021.09.0+351 or newer cause the problem.
Installing RStudio 1.4.X on `rocker/r-ver:4.2` may be a workaround.

```dockerfile
FROM rocker/r-ver:4.2
RUN /rocker_scripts/install_rstudio 1.4.1743
```

**Comment by ryao-mdanderson** [comment] 2022-06-02 13:51
@eitsupi Thanks for a workaround. We (HPC admin and the cluster users) usually pull a prebuilt rstudio image directly from docker://rocker, if possible, please create a new R studio 4.2 container that working with singularity. I would be happy to test that.

**Comment by eitsupi** [comment] 2022-06-04 15:08
I noticed in this comment (https://github.com/rocker-org/rocker-versioned2/issues/105#issuecomment-1015338996) that it is reported to work with RStudio Server 2021.09 or later.
@ryao-mdanderson Have you tried this approach?
If you are trying, I suggest you detail the problem in the issue.

I would like to close this issue as a duplicate for now.

Duplicate of #105

**Closed by eitsupi** 2022-06-04 15:08 UTC
Labels: help wanted, question, needs more info

**Comment by ryao-mdanderson** [comment] 2022-06-05 22:14
@eitsupi You are right. I reviewed the post in #105 again, notice I was missing "--server-user ${USER}" pass to singularity exec command. I tested rstudio versions 4.1.1 and 4.2.0, they both work now. Again. Thanks for your helps, direct me to the useful posting.

**Comment by eitsupi** [comment] 2022-06-06 01:42
I'm glad to hear that!
Thanks for letting us know what's going on.
