### ISSUE TITLE
shiny-verse with Ubuntu 18.04

### ISSUE THREAD

**Issue by jamessmythe** [rocker-org/rocker-versioned2#357] opened 2021-06-30 16:21 UTC
I’ve been having trouble connecting to a database with ODBC Driver 17 with an app built on rocker/shiny-verse. I got an expert to help me but he found an issue with the version of Ubuntu (20.04) which I think is packaged with this, which prevents us from connecting to the database.

https://github.com/r-dbi/odbc/issues/460

I tried building my image from rocker/tidyverse:4.0.0-ubuntu18.04 and loading shiny separately - this seems to have solved the database connection issue but has led onto all sorts of missing functions which you have no doubt covered in shiny-verse.

Do you know if there is a version of shiny-verse with Ubuntu 18.04 please?

**Comment by eitsupi** [comment] 2022-02-21 14:00
Currently, only the Ubuntu 18.04-based `rocker/shiny-verse:4.0.0` exists and is being built regularly.
https://github.com/rocker-org/rocker-versioned2/wiki

I will close this issue, but please let me know if the problem is still unresolved so I can reopen it.

**Closed by eitsupi** 2022-02-21 14:00 UTC
